routes/admin.php
<?php

Route::group(["namespace" => "Admin", 'middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/home', 'HomeController@index')->name("home");
    Route::get('/', 'HomeController@index')->name("home");

    // Admin
    Route::resource("admins", "AdminController");

    // Comapany
    Route::get('/companies', 'CompaniesController@index')->name("companies");
    Route::get('/companies/add_company', 'CompaniesController@add_company')->name("add_company");
    Route::post('/companies/save_company', 'CompaniesController@save_company')->name("save_company");
    Route::get('/companies/edit_company/{id?}', 'CompaniesController@edit_company')->name("edit_company");
    Route::post('/companies/update_company', 'CompaniesController@update_company')->name("update_company");
    Route::get('/companies/delete_company/{id?}', 'CompaniesController@delete_company')->name("delete_company");

    // Users
    Route::resource("users", "UserController");

    // Clients
    Route::resource("clients", "ClientController");

    // messages
    Route::resource("messages", "MessageController");

    // Settings
    Route::get('/settings', 'SettingsController@index')->name("settings.index");
    //Route::post('/save_generals_smtp', 'SettingsController@save_generals_smtp')->name("settings.save_generals_smtp");
    //Route::post('/save_generals_nexmo', 'SettingsController@save_generals_nexmo')->name("settings.save_generals_nexmo");
    //Route::post('/save_pusher', 'SettingsController@save_pusher')->name("settings.save_pusher");

});

routes/web.php
<?php


//Auth
Auth::routes();
Route::post('/verification/{id}', 'Auth\LoginController@verifyUser')->name('verification');
Route::get('/resend/{id}', 'Auth\LoginController@resendVerificationCode')->name('resend');
Route::get('/send_new/{id}', 'Auth\LoginController@sendNewVerificationCode')->name('send_new');





Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/contact', 'HomeController@contact')->name('contact');
Route::get('/cronjob', 'HomeController@cronjob')->name('cronjob');

Route::get('company/password/reset/{token}', "HomeController@showResetForm")->name("company.password.reset");
Route::post('company/password/reset', "HomeController@reset")->name("company.password.update");

require ("admin.php");

require ("company/company.php");

Route::get('/cmd', function (){
    //return shell_exec("php composer.phar -v");
    phpinfo();
});

Route::get("/meeting/{meeting?}/{user_id?}", "HomeController@meeting")->name("meeting_url");
Route::post("/save_invited", "HomeController@save_invited")->name("save_invited");
Route::get("/reminder", "HomeController@reminder")->name("reminder");

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Company;

class ClientController extends Controller
{
    public function index(){
        $clients = User::where("type", 1)->with("company")->orderby("id", "desc")->get();

        return view("admin.clients.index", compact("clients"));
    }

    public function create(){
        $companies = Company::orderby("name", "asc")->get();

        return view("admin.clients.create", compact("companies"));
    }

    public function store(Request $request){
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required|string|unique:users',
            'password' => 'required|string|min:6',
            'company_id' => 'required',
            'image' => 'required|image',
        ]);
        $client            = new User;
        $client->name        = $request->name;
        $client->email       = $request->email;
        $client->phone       = $request->phone;
        $client->role_id     = 0;
        $client->type        = 1;
        $client->password    = bcrypt($request->password);
        $client->company_id  = $request->company_id;
        $path = $request->file('image')->store('uploads/clients');
        $client->image = $path;
        $client->save();

        return redirect()->route("admin.clients.index")->with("success", "تم حفظ العميل الجديد !");
    }

    public function show($id){
        //
    }

    public function edit($id=null){
        $client = User::find($id);
        if(!$id or !$client)
            return redirect()->back();
        $companies = Company::orderby("name", "asc")->get();

        return view("admin.clients.edit", compact("client", "companies"));
    }

    public function update(Request $request, $id){
        $client = User::find($id);
        if(!$id or !$client)
            return redirect()->back();

        $request->validate(['name' => 'required|string|max:255', 'email' => 'required|string|email|max:255','company_id' => 'required',]);
        if($request->password)
            $request->validate(['password' => 'required|string|min:6']);

        $other = User::where("email", $request->email)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "البريد الإلكتروني مستعمل !");

        $other = User::where("phone", $request->phone)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "رقم الجوال مستعمل !");

        $client->name        = $request->name;
        $client->email       = $request->email;
        $client->phone       = $request->phone;
        $client->company_id       = $request->company_id;
        if($request->password)
            $client->password    = bcrypt($request->password);
        if($request->hasFile("image")){
            $request->validate(['image' => 'required|image']);
            $path = $request->file('image')->store('uploads/clients');
            $client->image = $path;
        }
        $client->save();

        return redirect()->back()->with("success", "تم تعديل بيانات العميل !");
    }

    public function destroy($id){
        $client = User::find($id);
        $client->delete();

        return redirect()->route("admin.clients.index")->with("success", "تم حذف العميل !");
    }
}

app/Http/Controllers/Company/ClientController.php
<?php

namespace App\Http\Controllers\Company;

use Illuminate\Http\Request;
use App\Http\Controllers\Company\Companies;
use App\User;
use App\Company;

class ClientController extends Companies
{
    public function __construct(){
        parent::__construct();
    }

    public function index(){
        $clients = User::where("type", 1)->where("company_id", @$this->company->id)->with("company")->orderby("id", "desc")->get();
        $company = $this->company;

        return view("company.clients.index", compact("clients", "company"));
    }

    public function create(){
        if(!permissions_general("add_client"))
            return back();
        $companies = Company::orderby("name", "asc")->get();
        $company = $this->company;

        return view("company.clients.create", compact("companies", "company"));
    }

    public function store(Request $request){
        if(!permissions_general("add_client"))
            return back();
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required|string|max:255|unique:users',
            'password' => 'required|string|min:6',
            'company_id' => 'required',
            'image' => 'required|image',
        ]);
        $client            = new User;
        $client->name        = $request->name;
        $client->email       = $request->email;
        $client->phone       = $request->phone;
        $client->role_id        = $request->role;
        $client->status      = $request->status;
        $client->type        = 1;
        $client->password    = bcrypt($request->password);
        $client->company_id       = $request->company_id;
        $path = $request->file('image')->store('uploads/clients');
        $client->image = $path;
        $client->save();

        return redirect()->back()->with("success", "تم حفظ العميل الجديد !");
    }

    public function show($c, $id){
        if(!permissions_general("show_client"))
            return back();
        $user = User::with("role")->where("type", 1)->where("company_id", @$this->company->id)->where("id", $id)->first();
        $company = $this->company;

        return view("company.clients.show", compact("user", "company"));
    }

    public function edit($c, $id=null){
        if(!permissions_general("update_client"))
            return back();
        $client = User::find($id);
        if(!$id or !$client)
            return redirect()->back();
        $companies = Company::orderby("name", "asc")->get();
        $company = $this->company;

        return view("company.clients.edit", compact("client", "companies", "company"));
    }

    public function update(Request $request,$c, $id){
        if(!permissions_general("update_client"))
            return back();
        $client = User::find($id);
        if(!$id or !$client)
            return redirect()->back();

        $request->validate(['name' => 'required|string|max:255', 'email' => 'required|string|email|max:255']);
        if($request->password)
            $request->validate(['password' => 'required|string|min:6']);

        $other = User::where("email", $request->email)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "البريد الإلكتروني مستعمل !");

        $other = User::where("phone", $request->phone)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "رقم الجوال مستعمل !");

        $client->name        = $request->name;
        $client->email       = $request->email;
        $client->phone       = $request->phone;
        $client->role_id        = $request->role;
        $client->status      = $request->status;
        if($request->password)
            $client->password    = bcrypt($request->password);
        if($request->hasFile("image")){
            $request->validate(['image' => 'required|image']);
            $path = $request->file('image')->store('uploads/clients');
            $client->image = $path;
        }
        $client->save();

        return redirect()->back()->with("success", "تم تعديل بيانات العميل !");
    }

    public function destroy($c, $id){
        if(!permissions_general("delete_client"))
            return back();
        $client = User::find($id);
        $client->delete();

        return redirect()->back()->with("success", "تم حذف العميل !");
    }
}

resources/views/admin/clients/create.blade.php
@extends("admin.layouts.app", ["title"=>"إضافة عميل"])

@section("content")

    <section class="content-header">
        <h1>
            قائمة العملاء
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <b>إضافة عميل</b>
                        <a class="btn btn-default btn-xs pull-left" href="{{route("admin.clients.index")}}"><i class="fa fa-list"></i> <span>قائمة العملاء</span></a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">

                        <div class="row">

                            <div class="col-sm-7">

                                <form action="{{route("admin.clients.store")}}" method="post" enctype="multipart/form-data">
                                    @csrf

                                    <div class="form-group">
                                        <label for="name">الإسم</label>
                                        <input type="text" value="{{old('name')}}" name="name" id="name" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="phone">رقم الجوال</label>
                                        <input type="text" value="{{old('phone')}}" name="phone" id="phone" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="email">البريد الإلكتروني</label>
                                        <input type="email" value="{{old('email')}}" name="email" id="email" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="password">كلمة المرور</label>
                                        <input type="password" name="password" id="password" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="company_id">الشركة</label>
                                        <select name="company_id" id="company_id" class="form-control" required>
                                            @foreach($companies as $company)
                                                <option value="{{$company->id}}">{{$company->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label for="image">الصورة</label>
                                        <input type="file" accept="image/*" name="image" id="image" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary" style="width: 120px"><i class="fa fa-save"></i> <span>حفظ</span></button>
                                    </div>

                                </form>

                            </div>

                            <div class="col-sm-5"></div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/admin/clients/edit.blade.php
@extends("admin.layouts.app", ["title"=>"تعديل عميل"])

@section("content")

    <section class="content-header">
        <h1>
            قائمة العملاء
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <b>تعديل عميل</b>
                        <a class="btn btn-default btn-xs pull-left" href="{{route("admin.clients.index")}}"><i class="fa fa-list"></i> <span>قائمة العملاء</span></a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">

                        <div class="row">

                            <div class="col-sm-7">

                                <form action="{{route("admin.clients.update", $client->id)}}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    {{method_field("PUT")}}

                                    <div class="form-group">
                                        <label for="name">الإسم</label>
                                        <input type="text" name="name" id="name" value="{{$client->name}}" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="phone">رقم الجوال</label>
                                        <input type="text" value="{{$client->phone}}" name="phone" id="phone" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="email">البريد الإلكتروني</label>
                                        <input type="email" name="email" id="email" value="{{$client->email}}" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="password">كلمة المرور</label>
                                        <input type="password" name="password" id="password" class="form-control">
                                        <small>دع الحقل فارغا إذا لم تكن تريد تغيير كلمة المرور</small>
                                    </div>

                                    <div class="form-group">
                                        <label for="company_id">الشركة</label>
                                        <select name="company_id" id="company_id" class="form-control" required>
                                            @foreach($companies as $company)
                                                <option value="{{$company->id}}" @if($client->company_id==$company->id) selected @endif>{{$company->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label for="image">الصورة</label>
                                        <input type="file" accept="image/*" name="image" id="image" class="form-control">
                                        <br>
                                        @if($client->image)
                                            <img src="{{asset("storage/app/".$client->image)}}" style="width: 120px; height: 120px; border: 1px solid #eee;">
                                        @else
                                            <img src="{{asset("public/noimage.png")}}" style="width: 120px; height: 120px; border: 1px solid #eee;">
                                        @endif
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary" style="width: 120px"><i class="fa fa-save"></i> <span>حفظ</span></button>
                                    </div>

                                </form>

                            </div>

                            <div class="col-sm-5"></div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/admin/clients/index.blade.php
@extends("admin.layouts.app", ["title"=>"قائمة العملاء"])

@section("content")

    <section class="content-header">
        <h1>
            قائمة العملاء
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <b>قائمة العملاء</b>
                        <a class="btn btn-default btn-xs pull-left" href="@if(@$company){{route("company.clients.create", @$company->slug)}}@else{{route("admin.clients.create")}}@endif"><i class="fa fa-plus"></i> <span>إضافة عميل</span></a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <table id="dataTable" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th width="20px"></th>
                                    <th>الصورة</th>
                                    <th>الإسم</th>
                                    <th>البريد الإلكتروني</th>
                                    <th>الشركة</th>
                                    <th>الأوامر</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($clients as $client)
                                    <tr>
                                        <td class="text-center">{{$loop->iteration}}</td>
                                        <td>
                                            @if($client->image)
                                                <img src="{{asset("storage/app/".$client->image)}}" style="width: 40px; height: 40px; border-radius: 50%; border: 1px solid #eee; margin: 0px auto; display: block;">
                                            @else
                                                <img src="{{asset("public/noimage.png")}}" style="width: 40px; height: 40px; border-radius: 50%; border: 1px solid #eee; margin: 0px auto; display: block;">
                                            @endif
                                        </td>
                                        <td>{{$client->name}}</td>
                                        <td>{{$client->email}}</td>
                                        <td>{{@$client->company->name}}</td>
                                        <td>
                                            <a class="btn btn-success btn-xs" href="{{route("admin.clients.edit", $client->id)}}"><i class="fa fa-edit"></i> <span>تعديل</span></a>
                                            <a class="btn btn-danger btn-xs" href="javascript:void(0)" onclick="document.getElementById('deleteform{{$client->id}}').submit()"><i class="fa fa-trash"></i> <span>حذف</span></a>
                                            <form id="deleteform{{$client->id}}" action="{{route("admin.clients.destroy", $client->id)}}" method="post">@csrf {{method_field("DELETE")}}</form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection