routes/admin.php
<?php

Route::group(["namespace" => "Admin", 'middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/home', 'HomeController@index')->name("home");
    Route::get('/', 'HomeController@index')->name("home");

    // Admin
    Route::resource("admins", "AdminController");

    // Comapany
    Route::get('/companies', 'CompaniesController@index')->name("companies");
    Route::get('/companies/add_company', 'CompaniesController@add_company')->name("add_company");
    Route::post('/companies/save_company', 'CompaniesController@save_company')->name("save_company");
    Route::get('/companies/edit_company/{id?}', 'CompaniesController@edit_company')->name("edit_company");
    Route::post('/companies/update_company', 'CompaniesController@update_company')->name("update_company");
    Route::get('/companies/delete_company/{id?}', 'CompaniesController@delete_company')->name("delete_company");

    // Users
    Route::resource("users", "UserController");

    // Clients
    Route::resource("clients", "ClientController");

    // messages
    Route::resource("messages", "MessageController");

    // Settings
    Route::get('/settings', 'SettingsController@index')->name("settings.index");
    //Route::post('/save_generals_smtp', 'SettingsController@save_generals_smtp')->name("settings.save_generals_smtp");
    //Route::post('/save_generals_nexmo', 'SettingsController@save_generals_nexmo')->name("settings.save_generals_nexmo");
    //Route::post('/save_pusher', 'SettingsController@save_pusher')->name("settings.save_pusher");

});

routes/web.php
<?php


//Auth
Auth::routes();
Route::post('/verification/{id}', 'Auth\LoginController@verifyUser')->name('verification');
Route::get('/resend/{id}', 'Auth\LoginController@resendVerificationCode')->name('resend');
Route::get('/send_new/{id}', 'Auth\LoginController@sendNewVerificationCode')->name('send_new');





Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/contact', 'HomeController@contact')->name('contact');
Route::get('/cronjob', 'HomeController@cronjob')->name('cronjob');

Route::get('company/password/reset/{token}', "HomeController@showResetForm")->name("company.password.reset");
Route::post('company/password/reset', "HomeController@reset")->name("company.password.update");

require ("admin.php");

require ("company/company.php");

Route::get('/cmd', function (){
    //return shell_exec("php composer.phar -v");
    phpinfo();
});

Route::get("/meeting/{meeting?}/{user_id?}", "HomeController@meeting")->name("meeting_url");
Route::post("/save_invited", "HomeController@save_invited")->name("save_invited");
Route::get("/reminder", "HomeController@reminder")->name("reminder");

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
}

app/Http/Controllers/Admin/CompaniesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Company;
use App\User;

class CompaniesController extends Controller
{
    public function index(){
        $companies = Company::orderby("id", "desc")->get();

        return view("admin.companies.index", compact("companies"));
    }

    public function add_company(){
        return view("admin.companies.add");
    }

    public function save_company(Request $request){
        $request->validate(["name"=>"required|string"]);
        $request->validate(["slug"=>"required|string|unique:companies"]);
        $request->validate([
            'namex' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required|string|unique:users',
            'password' => 'required|string|min:6',
        ]);

        $company            = new Company;
        $company->name      = $request->name;
        $company->slug      = str_replace(" ", "", trim($request->slug));
        $company->meetings  = ($request->meetings)?1:0;
        $company->crm       = ($request->crm)?1:0;
        $company->prm       = ($request->prm)?1:0;
        $company->hrm       = ($request->hrm)?1:0;
        $company->cards     = ($request->cards)?1:0;
        $company->passwords = ($request->passwords)?1:0;

        if($request->hasFile("image")){
            $request->validate(["image"=>"required|image"]);
            $path = $request->file('image')->store('uploads/companies');
            $company->image = $path;
        }

        $company->save();

        $user              = new User;
        $user->name        = $request->namex;
        $user->email       = $request->email;
        $user->phone       = $request->phone;
        $user->role_id     = 1;
        $user->type        = 0;
        $user->password    = bcrypt($request->password);
        $user->company_id       = $company->id;
        $user->save();

        return redirect()->route("admin.companies")->with("success", "تم إضافة الشركة بنجاح");
    }

    public function edit_company($id=null){
        $company = Company::find($id);
        if(!$id or !$company)
            return redirect()->back();

        return view("admin.companies.edit", compact("company"));
    }

    public function update_company(Request $request){
        $company = Company::find($request->id);
        if(!$request->id or !$company)
            return redirect()->back();

        $request->validate(["name"=>"required|string"]);
        $request->validate(["slug"=>"required|string"]);
        $others = Company::where("slug", $request->slug)->where("id", "!=", $request->id)->first();
        if($others)
            return redirect()->back()->with("error", "الرابط مستعمل من قبل");

        $company->name      = $request->name;
        $company->slug      = str_replace(" ", "", trim($request->slug));
        $company->meetings  = ($request->meetings)?1:0;
        $company->crm       = ($request->crm)?1:0;
        $company->prm       = ($request->prm)?1:0;
        $company->hrm       = ($request->hrm)?1:0;
        $company->cards     = ($request->cards)?1:0;
        $company->passwords = ($request->passwords)?1:0;

        if($request->hasFile("image")){
            $request->validate(["image"=>"required|image"]);
            $path = $request->file('image')->store('uploads/companies');
            $company->image = $path;
        }

        $company->save();

        return redirect()->back()->with("success", "تم تعديل الشركة بنجاح");
    }
    
    public function delete_company($id=null){
        return back()->with("error", "لا يمكن حذف الشركات حاليا !");
    }

}

app/Http/Controllers/Company/ClientController.php
<?php

namespace App\Http\Controllers\Company;

use Illuminate\Http\Request;
use App\Http\Controllers\Company\Companies;
use App\User;
use App\Company;

class ClientController extends Companies
{
    public function __construct(){
        parent::__construct();
    }

    public function index(){
        $clients = User::where("type", 1)->where("company_id", @$this->company->id)->with("company")->orderby("id", "desc")->get();
        $company = $this->company;

        return view("company.clients.index", compact("clients", "company"));
    }

    public function create(){
        if(!permissions_general("add_client"))
            return back();
        $companies = Company::orderby("name", "asc")->get();
        $company = $this->company;

        return view("company.clients.create", compact("companies", "company"));
    }

    public function store(Request $request){
        if(!permissions_general("add_client"))
            return back();
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required|string|max:255|unique:users',
            'password' => 'required|string|min:6',
            'company_id' => 'required',
            'image' => 'required|image',
        ]);
        $client            = new User;
        $client->name        = $request->name;
        $client->email       = $request->email;
        $client->phone       = $request->phone;
        $client->role_id        = $request->role;
        $client->status      = $request->status;
        $client->type        = 1;
        $client->password    = bcrypt($request->password);
        $client->company_id       = $request->company_id;
        $path = $request->file('image')->store('uploads/clients');
        $client->image = $path;
        $client->save();

        return redirect()->back()->with("success", "تم حفظ العميل الجديد !");
    }

    public function show($c, $id){
        if(!permissions_general("show_client"))
            return back();
        $user = User::with("role")->where("type", 1)->where("company_id", @$this->company->id)->where("id", $id)->first();
        $company = $this->company;

        return view("company.clients.show", compact("user", "company"));
    }

    public function edit($c, $id=null){
        if(!permissions_general("update_client"))
            return back();
        $client = User::find($id);
        if(!$id or !$client)
            return redirect()->back();
        $companies = Company::orderby("name", "asc")->get();
        $company = $this->company;

        return view("company.clients.edit", compact("client", "companies", "company"));
    }

    public function update(Request $request,$c, $id){
        if(!permissions_general("update_client"))
            return back();
        $client = User::find($id);
        if(!$id or !$client)
            return redirect()->back();

        $request->validate(['name' => 'required|string|max:255', 'email' => 'required|string|email|max:255']);
        if($request->password)
            $request->validate(['password' => 'required|string|min:6']);

        $other = User::where("email", $request->email)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "البريد الإلكتروني مستعمل !");

        $other = User::where("phone", $request->phone)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "رقم الجوال مستعمل !");

        $client->name        = $request->name;
        $client->email       = $request->email;
        $client->phone       = $request->phone;
        $client->role_id        = $request->role;
        $client->status      = $request->status;
        if($request->password)
            $client->password    = bcrypt($request->password);
        if($request->hasFile("image")){
            $request->validate(['image' => 'required|image']);
            $path = $request->file('image')->store('uploads/clients');
            $client->image = $path;
        }
        $client->save();

        return redirect()->back()->with("success", "تم تعديل بيانات العميل !");
    }

    public function destroy($c, $id){
        if(!permissions_general("delete_client"))
            return back();
        $client = User::find($id);
        $client->delete();

        return redirect()->back()->with("success", "تم حذف العميل !");
    }
}

app/Http/Controllers/Company/UserController.php
<?php

namespace App\Http\Controllers\Company;

use Illuminate\Http\Request;
use App\Http\Controllers\Company\Companies;
use App\User;
use App\Company;
use App\Role;

class UserController extends Companies
{
    public function __construct(){
        parent::__construct();
    }

    public function index(){
        $users = User::with("role")->where("type", 0)->where("company_id", @$this->company->id)->with("company")->orderby("id", "desc")->get();
        $company = $this->company;

        return view("company.users.index", compact("users", "company"));
    }

    public function create(){
        if(!permissions_general("add_user"))
            return back();
        $companies = Company::orderby("name", "asc")->get();
        $company = $this->company;
        $roles = Role::where("company_id", $company->id)->orderby("name", "asc")->where("id", "!=", 1)->get();

        return view("company.users.create", compact("companies", "company", "roles"));
    }

    public function store(Request $request){
        if(!permissions_general("add_user"))
            return back();
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required|string|max:255|unique:users',
            'password' => 'required|string|min:6',
            'company_id' => 'required',
            'image' => 'required|image',
        ]);
        $user              = new User;
        $user->name        = $request->name;
        $user->email       = $request->email;
        $user->phone       = $request->phone;
        $user->role_id     = $request->role;
        $user->status      = $request->status;
        $user->type        = 0;
        $user->password    = bcrypt($request->password);
        $user->company_id       = $request->company_id;
        $path = $request->file('image')->store('uploads/users');
        $user->image = $path;
        $user->save();

        return redirect()->back()->with("success", "تم حفظ الموظف الجديد !");
    }

    public function show($c, $id){
        if(!permissions_general("show_user"))
            return back();
        $user = User::with("role")->where("type", 0)->where("company_id", @$this->company->id)->where("id", $id)->first();
        $company = $this->company;

        return view("company.users.show", compact("user", "company"));
    }

    public function edit($c,$id=null){
        if(!permissions_general("update_user"))
            return back();
        $user = User::find($id);
        if(!$id or !$user)
            return redirect()->back();
        $companies = Company::orderby("name", "asc")->get();
        $company = $this->company;
        $roles = Role::where("company_id", $company->id)->orderby("name", "asc")->where("id", "!=", 1)->get();

        return view("company.users.edit", compact("user", "companies", "company", "roles"));
    }

    public function update(Request $request,$c, $id){
        if(!permissions_general("update_user"))
            return back();
        $user = User::find($id);
        if(!$id or !$user)
            return redirect()->back();

        $request->validate(['name' => 'required|string|max:255', 'email' => 'required|string|email|max:255', 'phone' => 'required|string|max:255']);
        if($request->password)
            $request->validate(['password' => 'required|string|min:6']);

        $other = User::where("email", $request->email)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "البريد الإلكتروني مستعمل !");

        $other = User::where("phone", $request->phone)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "رقم الجوال مستعمل !");

        $user->name        = $request->name;
        $user->email       = $request->email;
        $user->phone       = $request->phone;
        $user->role_id     = $request->role;
        $user->status      = $request->status;
        if($request->password)
            $user->password    = bcrypt($request->password);
        if($request->hasFile("image")){
            $request->validate(['image' => 'required|image']);
            $path = $request->file('image')->store('uploads/users');
            $user->image = $path;
        }
        $user->save();

        return redirect()->back()->with("success", "تم تعديل بيانات الموظف !");
    }

    public function destroy($c, $id){
        if(!permissions_general("delete_user"))
            return back();
        $user = User::find($id);
        $user->delete();

        return redirect()->back()->with("success", "تم حذف الموظف !");
    }
}

resources/views/admin/companies/add.blade.php
@extends("admin.layouts.app", ["title"=>"إضافة شركة"])

@section("content")

    <section class="content-header">
        <h1>
            الشركات
            <small>إضافة شركة</small>
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <b>إضافة شركة</b>
                        <a class="btn btn-success btn-xs pull-left" href="{{route("admin.companies")}}"><i class="fa fa-reply"></i> <span>العودة للقائمة</span></a>
                    </div>
                    <div class="panel-body">

                        <div class="row">

                            <form action="{{route("admin.save_company")}}" method="post" enctype="multipart/form-data">
                                @csrf

                                <div class="col-sm-4">

                                    <div class="form-group">
                                        <label>الدفاتر المسموح بها لهذه الشركة</label>
                                        <div class="checkbox icheck"><label><input class="form-check-input" type="checkbox" name="meetings"> <strong>نظام إجتماعاتي</strong></label></div>
                                        <div class="checkbox icheck"><label><input class="form-check-input" type="checkbox" name="crm"> <strong>نظام إدارة علاقات العملاء</strong></label></div>
                                        <div class="checkbox icheck"><label><input class="form-check-input" type="checkbox" name="prm"> <strong>نظام إدارة المشاريع</strong></label></div>
                                        <div class="checkbox icheck"><label><input class="form-check-input" type="checkbox" name="hrm"> <strong>نظام شؤون الموظفين</strong></label></div>
                                        <div class="checkbox icheck"><label><input class="form-check-input" type="checkbox" name="cards"> <strong>بطاقة إهداءاتي</strong></label></div>
                                        <div class="checkbox icheck"><label><input class="form-check-input" type="checkbox" name="passwords"> <strong>نظام باسوورداتي</strong></label></div>
                                    </div>

                                </div>

                                <div class="col-sm-4">

                                    <div class="form-group">
                                        <h4>بيانات الشركة</h4>
                                    </div>

                                    <div class="form-group">
                                        <label>الإسم</label>
                                        <input type="text" name="name" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label>الرابط</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control" name="slug" required placeholder="thelink" style="text-align: left">
                                            <span class="input-group-addon" style="border-left: 1px solid #d2d6de;direction: initial;padding: 6px 30px 6px 30px;">{{url('/')}}/</span>
                                        </div>
                                        <small>يجب أن يكون أحرف لاتينية فقط</small>
                                    </div>

                                    <div class="form-group">
                                        <label>الشعار</label>
                                        <input type="file" name="image" accept="image/*" class="form-control">
                                    </div>

                                </div>

                                <div class="col-sm-4">

                                    <div class="form-group">
                                        <h4>بيانات الأدمن</h4>
                                    </div>

                                    <div class="form-group">
                                        <label for="namex">الإسم</label>
                                        <input type="text" value="{{old('namex')}}" name="namex" id="namex" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="phone">رقم الجوال</label>
                                        <input type="text" value="{{old('phone')}}" name="phone" id="phone" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="email">البريد الإلكتروني</label>
                                        <input type="email" value="{{old('email')}}" name="email" id="email" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="password">كلمة المرور</label>
                                        <input type="password" name="password" id="password" class="form-control" required>
                                    </div>

                                </div>

                                <div class="col-sm-12">
                                    <div class="form-group mt-20">
                                        <hr>
                                        <button type="submit" class="btn btn-primary" style="width: 120px;">حفظ</button>
                                    </div>
                                </div>

                            </form>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

@section("scripts")

    <link rel="stylesheet" href="{{asset("public/plugins/iCheck/square/blue.css")}}">
    <script src="{{asset("public/plugins/iCheck/icheck.min.js")}}"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
@endsection

resources/views/admin/companies/index.blade.php
@extends("admin.layouts.app", ["title"=>"الشركات"])

@section("content")

    <section class="content-header">
        <h1>
            الشركات
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <b>قائمة الشركات</b>
                        <a class="btn btn-success btn-xs pull-left" href="{{route("admin.add_company")}}"><i class="fa fa-plus"></i> <span>إضافة شركة</span></a>
                    </div>
                    <div class="panel-body">

                        <table class="table table-bordered" id="dataTable">
                            <thead>
                                <tr>
                                    <th width="10"></th>
                                    <th>الشعار</th>
                                    <th>الإسم</th>
                                    <th>الرابط</th>
                                    <th>الدفاتر</th>
                                    <th>الأوامر</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($companies as $company)
                                    <tr>
                                        <td class="text-center">{{$loop->iteration}}</td>
                                        <td>
                                            @if($company->image)
                                                <img src="{{asset("storage/app/".$company->image)}}" style="width: 80px; height: 80px; border: 1px solid #c3c3c3; border-radius: 50%; display: block; margin: 0px auto;">
                                            @else
                                                <img src="{{asset("public/uploads/logo2.png")}}" style="width: 80px; height: 80px; border: 1px solid #c3c3c3; border-radius: 50%; display: block; margin: 0px auto;">
                                            @endif
                                        </td>
                                        <td>{{$company->name}}</td>
                                        <td><a href="{{route("company.login", $company->slug)}}" target="_blank">{{route("company.login", $company->slug)}}</a></td>
                                        <td>
                                            @if($company->meetings) <strong style="display: block;">نظام إجتماعاتي</strong> @endif
                                            @if($company->crm) <strong style="display: block;">نظام إدارة علاقات العملاء</strong> @endif
                                            @if($company->prm) <strong style="display: block;">نظام إدارة المشاريع</strong> @endif
                                            @if($company->hrm) <strong style="display: block;">نظام شؤون الموظفين</strong> @endif
                                            @if($company->cards) <strong style="display: block;">بطاقة إهداءاتي</strong> @endif
                                            @if($company->passwords) <strong style="display: block;">نظام باسوورداتي</strong> @endif
                                        </td>
                                        <td>
                                            <a class="btn btn-xs btn-success" href="{{route("admin.edit_company", $company->id)}}"><i class="fa fa-edit"></i> <span>تعديل</span></a>
                                            <a class="btn btn-xs btn-danger" href="{{route("admin.delete_company", $company->id)}}"
                                            onclick="return confirm('هل أنت متأكد ؟')"><i class="fa fa-trash"></i> <span>حذف</span></a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection