routes/admin.php
<?php

Route::group(["namespace" => "Admin", 'middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/home', 'HomeController@index')->name("home");
    Route::get('/', 'HomeController@index')->name("home");

    // Admin
    Route::resource("admins", "AdminController");

    // Comapany
    Route::get('/companies', 'CompaniesController@index')->name("companies");
    Route::get('/companies/add_company', 'CompaniesController@add_company')->name("add_company");
    Route::post('/companies/save_company', 'CompaniesController@save_company')->name("save_company");
    Route::get('/companies/edit_company/{id?}', 'CompaniesController@edit_company')->name("edit_company");
    Route::post('/companies/update_company', 'CompaniesController@update_company')->name("update_company");
    Route::get('/companies/delete_company/{id?}', 'CompaniesController@delete_company')->name("delete_company");

    // Users
    Route::resource("users", "UserController");

    // Clients
    Route::resource("clients", "ClientController");

    // messages
    Route::resource("messages", "MessageController");

    // Settings
    Route::get('/settings', 'SettingsController@index')->name("settings.index");
    //Route::post('/save_generals_smtp', 'SettingsController@save_generals_smtp')->name("settings.save_generals_smtp");
    //Route::post('/save_generals_nexmo', 'SettingsController@save_generals_nexmo')->name("settings.save_generals_nexmo");
    //Route::post('/save_pusher', 'SettingsController@save_pusher')->name("settings.save_pusher");

});

routes/web.php
<?php


//Auth
Auth::routes();
Route::post('/verification/{id}', 'Auth\LoginController@verifyUser')->name('verification');
Route::get('/resend/{id}', 'Auth\LoginController@resendVerificationCode')->name('resend');
Route::get('/send_new/{id}', 'Auth\LoginController@sendNewVerificationCode')->name('send_new');





Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/contact', 'HomeController@contact')->name('contact');
Route::get('/cronjob', 'HomeController@cronjob')->name('cronjob');

Route::get('company/password/reset/{token}', "HomeController@showResetForm")->name("company.password.reset");
Route::post('company/password/reset', "HomeController@reset")->name("company.password.update");

require ("admin.php");

require ("company/company.php");

Route::get('/cmd', function (){
    //return shell_exec("php composer.phar -v");
    phpinfo();
});

Route::get("/meeting/{meeting?}/{user_id?}", "HomeController@meeting")->name("meeting_url");
Route::post("/save_invited", "HomeController@save_invited")->name("save_invited");
Route::get("/reminder", "HomeController@reminder")->name("reminder");

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Company;

class ClientController extends Controller
{
    public function index(){
        $clients = User::where("type", 1)->with("company")->orderby("id", "desc")->get();

        return view("admin.clients.index", compact("clients"));
    }

    public function create(){
        $companies = Company::orderby("name", "asc")->get();

        return view("admin.clients.create", compact("companies"));
    }

    public function store(Request $request){
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required|string|unique:users',
            'password' => 'required|string|min:6',
            'company_id' => 'required',
            'image' => 'required|image',
        ]);
        $client            = new User;
        $client->name        = $request->name;
        $client->email       = $request->email;
        $client->phone       = $request->phone;
        $client->role_id     = 0;
        $client->type        = 1;
        $client->password    = bcrypt($request->password);
        $client->company_id  = $request->company_id;
        $path = $request->file('image')->store('uploads/clients');
        $client->image = $path;
        $client->save();

        return redirect()->route("admin.clients.index")->with("success", "تم حفظ العميل الجديد !");
    }

    public function show($id){
        //
    }

    public function edit($id=null){
        $client = User::find($id);
        if(!$id or !$client)
            return redirect()->back();
        $companies = Company::orderby("name", "asc")->get();

        return view("admin.clients.edit", compact("client", "companies"));
    }

    public function update(Request $request, $id){
        $client = User::find($id);
        if(!$id or !$client)
            return redirect()->back();

        $request->validate(['name' => 'required|string|max:255', 'email' => 'required|string|email|max:255','company_id' => 'required',]);
        if($request->password)
            $request->validate(['password' => 'required|string|min:6']);

        $other = User::where("email", $request->email)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "البريد الإلكتروني مستعمل !");

        $other = User::where("phone", $request->phone)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "رقم الجوال مستعمل !");

        $client->name        = $request->name;
        $client->email       = $request->email;
        $client->phone       = $request->phone;
        $client->company_id       = $request->company_id;
        if($request->password)
            $client->password    = bcrypt($request->password);
        if($request->hasFile("image")){
            $request->validate(['image' => 'required|image']);
            $path = $request->file('image')->store('uploads/clients');
            $client->image = $path;
        }
        $client->save();

        return redirect()->back()->with("success", "تم تعديل بيانات العميل !");
    }

    public function destroy($id){
        $client = User::find($id);
        $client->delete();

        return redirect()->route("admin.clients.index")->with("success", "تم حذف العميل !");
    }
}

app/Http/Controllers/Admin/CompaniesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Company;
use App\User;

class CompaniesController extends Controller
{
    public function index(){
        $companies = Company::orderby("id", "desc")->get();

        return view("admin.companies.index", compact("companies"));
    }

    public function add_company(){
        return view("admin.companies.add");
    }

    public function save_company(Request $request){
        $request->validate(["name"=>"required|string"]);
        $request->validate(["slug"=>"required|string|unique:companies"]);
        $request->validate([
            'namex' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required|string|unique:users',
            'password' => 'required|string|min:6',
        ]);

        $company            = new Company;
        $company->name      = $request->name;
        $company->slug      = str_replace(" ", "", trim($request->slug));
        $company->meetings  = ($request->meetings)?1:0;
        $company->crm       = ($request->crm)?1:0;
        $company->prm       = ($request->prm)?1:0;
        $company->hrm       = ($request->hrm)?1:0;
        $company->cards     = ($request->cards)?1:0;
        $company->passwords = ($request->passwords)?1:0;

        if($request->hasFile("image")){
            $request->validate(["image"=>"required|image"]);
            $path = $request->file('image')->store('uploads/companies');
            $company->image = $path;
        }

        $company->save();

        $user              = new User;
        $user->name        = $request->namex;
        $user->email       = $request->email;
        $user->phone       = $request->phone;
        $user->role_id     = 1;
        $user->type        = 0;
        $user->password    = bcrypt($request->password);
        $user->company_id       = $company->id;
        $user->save();

        return redirect()->route("admin.companies")->with("success", "تم إضافة الشركة بنجاح");
    }

    public function edit_company($id=null){
        $company = Company::find($id);
        if(!$id or !$company)
            return redirect()->back();

        return view("admin.companies.edit", compact("company"));
    }

    public function update_company(Request $request){
        $company = Company::find($request->id);
        if(!$request->id or !$company)
            return redirect()->back();

        $request->validate(["name"=>"required|string"]);
        $request->validate(["slug"=>"required|string"]);
        $others = Company::where("slug", $request->slug)->where("id", "!=", $request->id)->first();
        if($others)
            return redirect()->back()->with("error", "الرابط مستعمل من قبل");

        $company->name      = $request->name;
        $company->slug      = str_replace(" ", "", trim($request->slug));
        $company->meetings  = ($request->meetings)?1:0;
        $company->crm       = ($request->crm)?1:0;
        $company->prm       = ($request->prm)?1:0;
        $company->hrm       = ($request->hrm)?1:0;
        $company->cards     = ($request->cards)?1:0;
        $company->passwords = ($request->passwords)?1:0;

        if($request->hasFile("image")){
            $request->validate(["image"=>"required|image"]);
            $path = $request->file('image')->store('uploads/companies');
            $company->image = $path;
        }

        $company->save();

        return redirect()->back()->with("success", "تم تعديل الشركة بنجاح");
    }
    
    public function delete_company($id=null){
        return back()->with("error", "لا يمكن حذف الشركات حاليا !");
    }

}

app/Http/Controllers/Company/ClientController.php
<?php

namespace App\Http\Controllers\Company;

use Illuminate\Http\Request;
use App\Http\Controllers\Company\Companies;
use App\User;
use App\Company;

class ClientController extends Companies
{
    public function __construct(){
        parent::__construct();
    }

    public function index(){
        $clients = User::where("type", 1)->where("company_id", @$this->company->id)->with("company")->orderby("id", "desc")->get();
        $company = $this->company;

        return view("company.clients.index", compact("clients", "company"));
    }

    public function create(){
        if(!permissions_general("add_client"))
            return back();
        $companies = Company::orderby("name", "asc")->get();
        $company = $this->company;

        return view("company.clients.create", compact("companies", "company"));
    }

    public function store(Request $request){
        if(!permissions_general("add_client"))
            return back();
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required|string|max:255|unique:users',
            'password' => 'required|string|min:6',
            'company_id' => 'required',
            'image' => 'required|image',
        ]);
        $client            = new User;
        $client->name        = $request->name;
        $client->email       = $request->email;
        $client->phone       = $request->phone;
        $client->role_id        = $request->role;
        $client->status      = $request->status;
        $client->type        = 1;
        $client->password    = bcrypt($request->password);
        $client->company_id       = $request->company_id;
        $path = $request->file('image')->store('uploads/clients');
        $client->image = $path;
        $client->save();

        return redirect()->back()->with("success", "تم حفظ العميل الجديد !");
    }

    public function show($c, $id){
        if(!permissions_general("show_client"))
            return back();
        $user = User::with("role")->where("type", 1)->where("company_id", @$this->company->id)->where("id", $id)->first();
        $company = $this->company;

        return view("company.clients.show", compact("user", "company"));
    }

    public function edit($c, $id=null){
        if(!permissions_general("update_client"))
            return back();
        $client = User::find($id);
        if(!$id or !$client)
            return redirect()->back();
        $companies = Company::orderby("name", "asc")->get();
        $company = $this->company;

        return view("company.clients.edit", compact("client", "companies", "company"));
    }

    public function update(Request $request,$c, $id){
        if(!permissions_general("update_client"))
            return back();
        $client = User::find($id);
        if(!$id or !$client)
            return redirect()->back();

        $request->validate(['name' => 'required|string|max:255', 'email' => 'required|string|email|max:255']);
        if($request->password)
            $request->validate(['password' => 'required|string|min:6']);

        $other = User::where("email", $request->email)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "البريد الإلكتروني مستعمل !");

        $other = User::where("phone", $request->phone)->where("id", "!=", $id)->first();
        if($other)
            return redirect()->back()->with("error", "رقم الجوال مستعمل !");

        $client->name        = $request->name;
        $client->email       = $request->email;
        $client->phone       = $request->phone;
        $client->role_id        = $request->role;
        $client->status      = $request->status;
        if($request->password)
            $client->password    = bcrypt($request->password);
        if($request->hasFile("image")){
            $request->validate(['image' => 'required|image']);
            $path = $request->file('image')->store('uploads/clients');
            $client->image = $path;
        }
        $client->save();

        return redirect()->back()->with("success", "تم تعديل بيانات العميل !");
    }

    public function destroy($c, $id){
        if(!permissions_general("delete_client"))
            return back();
        $client = User::find($id);
        $client->delete();

        return redirect()->back()->with("success", "تم حذف العميل !");
    }
}

resources/views/company/clients/create.blade.php
@extends("company.layouts.app", ["title"=>"إضافة عميل"])

@section("content")

    <section class="content-header">
        <h1>
            قائمة العملاء
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <b>إضافة عميل</b>
                        <a class="btn btn-default btn-xs pull-left" href="{{route("company.clients.index", $company->slug)}}"><i class="fa fa-list"></i> <span>قائمة العملاء</span></a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">

                        <div class="row">

                            <div class="col-sm-12">

                                <form action="{{route("company.clients.store", $company->slug)}}" method="post" enctype="multipart/form-data" style="padding: 0px 0px 40px 20px">
                                    @csrf
                                    <input type="hidden" value="{{$company->id}}" name="company_id" id="company_id" class="form-control" required>

                                    <div class="row">

                                        <div class="col-sm-6">

                                            <div class="form-group row mt-10">
                                                <label class="col-sm-4" for="name">الإسم <span class="red">*</span></label>
                                                <input type="text" value="{{old('name')}}" name="name" id="name" class="form-control col-sm-8" required>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-sm-4" for="role">المسمى <span class="red">*</span></label>
                                                <select name="role" id="role" class="form-control col-sm-8" required>
                                                    <option value="">إختر</option>
                                                    <option value="0">عميل فرد</option>
                                                    <option value="1">عميل شركة</option>
                                                    <option value="2">عميل جهة خيرية</option>
                                                </select>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-sm-4" for="image">الصورة <span class="red">*</span></label>
                                                <input type="file" accept="image/*" name="image" id="image" class="form-control col-sm-8" required>
                                            </div>

                                        </div>

                                        <div class="col-sm-6">

                                            <div class="form-group mt-10 row">
                                                <label class="col-sm-4" for="email">البريد الإلكتروني <span class="red">*</span></label>
                                                <input type="email" value="{{old('email')}}" name="email" id="email" class="form-control col-sm-8" required>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-sm-4" for="phone">رقم الجوال <span class="red">*</span></label>
                                                <input type="text" value="{{old('phone')}}" name="phone" id="phone" class="form-control col-sm-8" required>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-sm-4" for="status"> الحالة <span class="red">*</span></label>
                                                <select  name="status" id="status" class="form-control col-sm-8" required>
                                                    <option value="">إختر</option>
                                                    <option value="1">فعال</option>
                                                    <option value="0">موقوف</option>
                                                </select>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-sm-4" for="password">كلمة المرور <span class="red">*</span></label>
                                                <input type="password" name="password" id="password" class="form-control col-sm-8" required>
                                            </div>

                                        </div>

                                        <div class="col-sm-9"></div>
                                        <div class="col-sm-3">
                                            <div class="form-group mt-20">
                                                <button type="submit" class="btn btn-primary pull-left" style="width: 120px"><i class="fa fa-save"></i> <span>حفظ</span></button>
                                            </div>
                                        </div>

                                    </div>

                                </form>

                            </div>

                            <div class="col-sm-5"></div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/company/clients/edit.blade.php
@extends("company.layouts.app", ["title"=>"تعديل عميل"])

@section("content")

    <section class="content-header">
        <h1>
            قائمة العملاء
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <b>تعديل عميل</b>
                        <a class="btn btn-default btn-xs pull-left" href="{{route("company.clients.index", $company->slug)}}"><i class="fa fa-list"></i> <span>قائمة العملاء</span></a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">

                        <div class="row">

                            <div class="col-sm-12">

                                <form action="{{route("company.clients.update", ["company"=>$company->slug, "user"=>$client->id])}}" method="post" enctype="multipart/form-data" style="padding: 0px 0px 40px 20px">
                                    @csrf
                                    {{method_field("PUT")}}

                                    <div class="row">

                                        <div class="col-sm-6">

                                            <div class="form-group row mt-10">
                                                <label class="col-sm-4" for="name">الإسم <span class="red">*</span></label>
                                                <input type="text" value="{{$client->name}}" name="name" id="name" class="form-control col-sm-8" required>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-sm-4" for="role">المسمى <span class="red">*</span></label>
                                                <select name="role" id="role" class="form-control col-sm-8" required>
                                                    <option value="">إختر</option>
                                                    <option value="0" @if($client->role_id==0) selected @endif>عميل فرد</option>
                                                    <option value="1" @if($client->role_id==1) selected @endif>عميل شركة</option>
                                                    <option value="2" @if($client->role_id==2) selected @endif>عميل جهة خيرية</option>
                                                </select>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-sm-4" for="image">الصورة </label>
                                                <input type="file" accept="image/*" name="image" id="image" class="form-control col-sm-8">
                                                <div class="col-sm-4"></div>
                                                <div class="col-sm-8 row mt-20">
                                                    @if($client->image)
                                                        <img src="{{asset("storage/app/".$client->image)}}" style="width: 120px; height: 120px; border: 1px solid #eee;">
                                                    @else
                                                        <img src="{{asset("public/noimage.png")}}" style="width: 120px; height: 120px; border: 1px solid #eee;">
                                                    @endif
                                                </div>
                                            </div>

                                        </div>

                                        <div class="col-sm-6">

                                            <div class="form-group mt-10 row">
                                                <label class="col-sm-4" for="email">البريد الإلكتروني <span class="red">*</span></label>
                                                <input type="email" value="{{$client->email}}" name="email" id="email" class="form-control col-sm-8" required>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-sm-4" for="phone">رقم الجوال <span class="red">*</span></label>
                                                <input type="text" value="{{$client->phone}}" name="phone" id="phone" class="form-control col-sm-8" required>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-sm-4" for="status"> الحالة <span class="red">*</span></label>
                                                <select  name="status" id="status" class="form-control col-sm-8" required>
                                                    <option value="">إختر</option>
                                                    <option value="1" @if($client->status==1) selected @endif>فعال</option>
                                                    <option value="0" @if($client->status==0) selected @endif>موقوف</option>
                                                </select>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-sm-4" for="password">كلمة المرور </label>
                                                <input type="password" name="password" id="password" class="form-control col-sm-8" autocomplete="off">
                                                <div class="col-sm-4"></div>
                                                <div class="col-sm-8">أترك الحقل فارغا إذا لم تكن تريد تغيير الحقل</div>
                                            </div>

                                        </div>

                                        <div class="col-sm-9"></div>
                                        <div class="col-sm-3">
                                            <div class="form-group mt-20">
                                                <button type="submit" class="btn btn-primary pull-left" style="width: 120px"><i class="fa fa-save"></i> <span>حفظ</span></button>
                                            </div>
                                        </div>

                                    </div>

                                </form>

                            </div>

                            <div class="col-sm-5"></div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/company/clients/show.blade.php
@extends("company.layouts.app", ["title"=>"عرض الموظف"])

@section("content")

    <section class="content-header">
        <h1>
            قائمة الموظفين
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <b>عرض الموظف</b>
                        <a class="btn btn-default btn-xs pull-left" href="{{route("company.clients.index", @$company->slug)}}"><i class="fa fa-list"></i> <span>قائمة العملاء</span></a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">

                        <div class="row">

                            <div class="col-sm-12">

                                @if($user->image)
                                    <img src="{{asset("storage/app/".$user->image)}}" style="width: 150px; height: 150px; border-radius: 50%; border: 1px solid #eee; margin: 10px auto; display: block;">
                                @else
                                    <img src="{{asset("public/noimage.png")}}" style="width: 150px; height: 150px; border-radius: 50%; border: 1px solid #eee; margin: 10px auto; display: block;">
                                @endif
                                <h4 class="mt-20 text-center">{{$user->name}}</h4>
                                <h5 class="mt-10 text-center"><i class="fa fa-at"></i> {{$user->email}}</h5>
                                <h5 class="mt-10 text-center"><i class="fa fa-phone"></i> {{$user->phone}}</h5>
                                </div>

                            </div>

                        </div>

                    </div>

                </div>
            </div>
        </div>
    </section>

@endsection