routes/admin.php
<?php

Route::group(["namespace" => "Admin", 'middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/home', 'HomeController@index')->name("home");
    Route::get('/', 'HomeController@index')->name("home");

    // Admin
    Route::resource("admins", "AdminController");

    // Comapany
    Route::get('/companies', 'CompaniesController@index')->name("companies");
    Route::get('/companies/add_company', 'CompaniesController@add_company')->name("add_company");
    Route::post('/companies/save_company', 'CompaniesController@save_company')->name("save_company");
    Route::get('/companies/edit_company/{id?}', 'CompaniesController@edit_company')->name("edit_company");
    Route::post('/companies/update_company', 'CompaniesController@update_company')->name("update_company");
    Route::get('/companies/delete_company/{id?}', 'CompaniesController@delete_company')->name("delete_company");

    // Users
    Route::resource("users", "UserController");

    // Clients
    Route::resource("clients", "ClientController");

    // messages
    Route::resource("messages", "MessageController");

    // Settings
    Route::get('/settings', 'SettingsController@index')->name("settings.index");
    //Route::post('/save_generals_smtp', 'SettingsController@save_generals_smtp')->name("settings.save_generals_smtp");
    //Route::post('/save_generals_nexmo', 'SettingsController@save_generals_nexmo')->name("settings.save_generals_nexmo");
    //Route::post('/save_pusher', 'SettingsController@save_pusher')->name("settings.save_pusher");

});

routes/web.php
<?php


//Auth
Auth::routes();
Route::post('/verification/{id}', 'Auth\LoginController@verifyUser')->name('verification');
Route::get('/resend/{id}', 'Auth\LoginController@resendVerificationCode')->name('resend');
Route::get('/send_new/{id}', 'Auth\LoginController@sendNewVerificationCode')->name('send_new');





Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/contact', 'HomeController@contact')->name('contact');
Route::get('/cronjob', 'HomeController@cronjob')->name('cronjob');

Route::get('company/password/reset/{token}', "HomeController@showResetForm")->name("company.password.reset");
Route::post('company/password/reset', "HomeController@reset")->name("company.password.update");

require ("admin.php");

require ("company/company.php");

Route::get('/cmd', function (){
    //return shell_exec("php composer.phar -v");
    phpinfo();
});

Route::get("/meeting/{meeting?}/{user_id?}", "HomeController@meeting")->name("meeting_url");
Route::post("/save_invited", "HomeController@save_invited")->name("save_invited");
Route::get("/reminder", "HomeController@reminder")->name("reminder");

resources/views/admin/admins/create.blade.php
@extends("admin.layouts.app", ["title"=>"إضافة مستخدم"])

@section("content")

    <section class="content-header">
        <h1>
            قائمة المستخدمين
            <small>(الأدمن)</small>
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <b>إضافة مستخدم</b>
                        <a class="btn btn-default btn-xs pull-left" href="{{route("admin.admins.index")}}"><i class="fa fa-list"></i> <span>قائمة المستخدمين</span></a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">

                        <div class="row">

                            <div class="col-sm-7">

                                <form action="{{route("admin.admins.store")}}" method="post">
                                    @csrf

                                    <div class="form-group">
                                        <label for="name">الإسم</label>
                                        <input type="text" name="name" id="name" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="name">رقم الجوال</label>
                                        <input type="text" name="phone" id="phone" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="email">البريد الإلكتروني</label>
                                        <input type="email" name="email" id="email" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="password">كلمة المرور</label>
                                        <input type="password" name="password" id="password" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary" style="width: 120px"><i class="fa fa-save"></i> <span>حفظ</span></button>
                                    </div>

                                </form>

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/admin/admins/edit.blade.php
@extends("admin.layouts.app", ["title"=>"تعديل مستخدم"])

@section("content")

    <section class="content-header">
        <h1>
            قائمة المستخدمين
            <small>(الأدمن)</small>
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <b>تعديل مستخدم</b>
                        <a class="btn btn-default btn-xs pull-left" href="{{route("admin.admins.index")}}"><i class="fa fa-list"></i> <span>قائمة المستخدمين</span></a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">

                        <div class="row">

                            <div class="col-sm-5"></div>

                            <div class="col-sm-7">

                                <form action="{{route("admin.admins.update", $admin->id)}}" method="post">
                                    @csrf
                                    {{method_field("PUT")}}

                                    <div class="form-group">
                                        <label for="name">الإسم</label>
                                        <input type="text" name="name" id="name" value="{{$admin->name}}" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="name">رقم الجوال</label>
                                        <input type="text" name="phone" id="phone" value="{{$admin->phone}}" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="email">البريد الإلكتروني</label>
                                        <input type="email" name="email" id="email" value="{{$admin->email}}" class="form-control" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="password">كلمة المرور</label>
                                        <input type="password" name="password" id="password" class="form-control">
                                        <small>دع الحقل فارغا إذا لم تكن تريد تغيير كلمة المرور</small>
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary" style="width: 120px"><i class="fa fa-save"></i> <span>حفظ</span></button>
                                    </div>

                                </form>

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/admin/admins/index.blade.php
@extends("admin.layouts.app", ["title"=>"قائمة المستخدمين"])

@section("content")

    <section class="content-header">
        <h1>
            قائمة المستخدمين
            <small>(الأدمن)</small>
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <b>قائمة المستخدمين</b>
                        <a class="btn btn-default btn-xs pull-left" href="{{route("admin.admins.create")}}"><i class="fa fa-plus"></i> <span>إضافة مستخدم</span></a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <table id="dataTable" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th width="20px"></th>
                                    <th>الإسم</th>
                                    <th>رقم الجوال</th>
                                    <th>البريد الإلكتروني</th>
                                    <th>الأوامر</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($admins as $admin)
                                    <tr>
                                        <td class="text-center">{{$loop->iteration}}</td>
                                        <td>{{$admin->name}}</td>
                                        <td>{{$admin->phone}}</td>
                                        <td>{{$admin->email}}</td>
                                        <td>
                                            <a class="btn btn-success btn-xs" href="{{route("admin.admins.edit", $admin->id)}}"><i class="fa fa-edit"></i> <span>تعديل</span></a>
                                            <a class="btn btn-danger btn-xs" href="javascript:void(0)" onclick="document.getElementById('deleteform{{$admin->id}}').submit()"><i class="fa fa-trash"></i> <span>حذف</span></a>
                                            <form id="deleteform{{$admin->id}}" action="{{route("admin.admins.destroy", $admin->id)}}" method="post">@csrf {{method_field("DELETE")}}</form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection